---
x-nautobot-base: &nautobot-base
  volumes:
    - "./nautobot_config.py:/opt/nautobot/nautobot_config.py"
    - "../:/source"

version: "3.4"
services:
  nautobot:
    healthcheck:
      disable: true
    command: "nautobot-server runserver 0.0.0.0:8080"
    <<: *nautobot-base
  celery_worker:
    <<: *nautobot-base
  worker:
    <<: *nautobot-base
